name: workflow-keep-alive
on:
  schedule:
    - cron:  '15 16 13 * *'
    
jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chris-gillatt/gamez-meme-bot@master
        with:
          API_KEY: ${{ secrets.WORKFLOW_KEEP_ALIVE_TOKEN }}
      - uses: gautamkrishnar/keepalive-workflow@1.0.10
